# Generated by Django 4.2 on 2024-11-06 05:52

import accounts.models
from django.db import migrations, models
import accounts.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=30, null=True, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=15, validators=[accounts.validators.PhoneValidator()])),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('last_login', models.DateField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'User',
            },
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('FM', 'Unset')], default='FM', max_length=2)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('newsletter', models.CharField(blank=True, choices=[('T', 'مشترک خبرنامه'), ('F', 'عدم اشتراک در خبرنامه')], default='F', max_length=5)),
                ('avatar', models.ImageField(default='no-image.jpg', height_field='image_height', upload_to='static/images/profile/20241106-055231', width_field='image_width')),
                ('image_width', models.PositiveIntegerField(default=65, editable=False)),
                ('image_height', models.PositiveIntegerField(default=65, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
