# Generated by Django 4.2 on 2024-10-13 15:51

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import shop.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('FM', 'Unset')], default='FM', max_length=2)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, validators=[shop.validators.PhoneValidator()])),
                ('email', models.EmailField(blank=True, max_length=30, null=True, unique=True, verbose_name='email address')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateField(blank=True, null=True)),
                ('newsletter', models.CharField(blank=True, choices=[('T', 'مشترک خبرنامه'), ('F', 'عدم اشتراک در خبرنامه')], default='F', max_length=5, null=True)),
                ('avatar', models.ImageField(default='no-image.jpg', height_field='image_height', upload_to='static/images/profile/20241013-155124', width_field='image_width')),
                ('image_width', models.PositiveIntegerField(default=65, editable=False)),
                ('image_height', models.PositiveIntegerField(default=65, editable=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name_plural': 'User',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True)),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, default='no-image.jpg', height_field='image_height', null=True, upload_to='static/images/logos/', width_field='image_width')),
                ('image_width', models.PositiveIntegerField(default=50, editable=False)),
                ('image_height', models.PositiveIntegerField(default=50, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('payed', models.CharField(choices=[('T', 'Payed'), ('F', 'Not Payed')], default='F', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Product Color', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Product Colors',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contact-us Table',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('off', models.IntegerField(default=0, help_text='Off-price')),
                ('expire', models.DateTimeField(verbose_name='Expire Date')),
            ],
            options={
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='Kala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True)),
                ('name', models.CharField(max_length=150)),
                ('mini_description', models.CharField(max_length=200)),
                ('pic0', models.ImageField(default='no-image.jpg', height_field='image_height', upload_to='static/images/products/20241013-155124', width_field='image_width')),
                ('pic1', models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20241013 - 155124')),
                ('pic2', models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20241013 - 155124')),
                ('pic3', models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20241013 - 155124')),
                ('pic4', models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20241013 - 155124')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('image_width', models.PositiveIntegerField(default=401, editable=False)),
                ('image_height', models.PositiveIntegerField(default=401, editable=False)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand', to='shop.brand', verbose_name='Brand')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='KalaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Product Materials', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Product Materials',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter title for Post', max_length=100)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('body', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('pic', models.ImageField(blank=True, default='no-image.jpg', height_field='image_height', null=True, upload_to='static/images/posts/20241013-155124', width_field='image_width')),
                ('image_width', models.PositiveIntegerField(blank=True, default=401, editable=False, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, default=401, editable=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Post',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_no', models.CharField(help_text='Enter a product size', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Product Sizes',
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.kala')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Wishlist',
            },
        ),
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FollowUpCode', models.CharField(default='3520241013155124', max_length=20)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(max_length=500)),
                ('zip_code', models.CharField(max_length=10, verbose_name='Zip Code')),
                ('city', models.CharField(max_length=50)),
                ('total_price', models.BigIntegerField(help_text='Total Price With offers & Coupons')),
                ('send_price', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('total', models.BigIntegerField(help_text='Total Price With offers, Coupons, tax & send price.')),
                ('desc', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('sent', models.CharField(choices=[('B', 'Back to Store'), ('F', 'Package Wait for send'), ('T', 'Package sent')], default='F', help_text='Is package sent?', max_length=1, verbose_name='Send Status')),
                ('products', models.ManyToManyField(to='shop.cart', verbose_name='Products')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.states')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
            ],
            options={
                'verbose_name_plural': 'Sold',
            },
        ),
        migrations.CreateModel(
            name='KalaInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField(verbose_name='Price')),
                ('off', models.IntegerField(default=0)),
                ('instock', models.IntegerField()),
                ('kala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kala_instance', to='shop.kala')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product Instances',
            },
        ),
        migrations.AddField(
            model_name='kala',
            name='category',
            field=models.ForeignKey(help_text='category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Category', to='shop.kalacategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='kala',
            name='color',
            field=models.ManyToManyField(help_text='Select Color of the product', to='shop.color'),
        ),
        migrations.AddField(
            model_name='kala',
            name='material',
            field=models.ManyToManyField(help_text='Select Material of the Product', to='shop.materials'),
        ),
        migrations.AddField(
            model_name='kala',
            name='size',
            field=models.ManyToManyField(help_text='Enter Size of the product', to='shop.productsize'),
        ),
        migrations.CreateModel(
            name='Compare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.kala')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Compare',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500)),
                ('data', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('T', "It's Ok"), ('W', 'Waiting')], default='W', max_length=1)),
                ('kala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.kala')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Color', to='shop.color'),
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.coupon'),
        ),
        migrations.AddField(
            model_name='cart',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Materials', to='shop.materials'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.kala', verbose_name='Products'),
        ),
        migrations.AddField(
            model_name='cart',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Instance', to='shop.kalainstance'),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductSize', to='shop.productsize'),
        ),
        migrations.AddField(
            model_name='cart',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.states'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
