# Generated by Django 4.2 on 2024-11-06 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True)),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, default='no-image.jpg', height_field='image_height', null=True, upload_to='static/images/logos/', width_field='image_width')),
                ('image_width', models.PositiveIntegerField(default=50, editable=False)),
                ('image_height', models.PositiveIntegerField(default=50, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('payed', models.CharField(choices=[('T', 'Payed'), ('F', 'Not Payed')], default='F', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Product Color', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Product Colors',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contact-us Table',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('off', models.IntegerField(default=0, help_text='Off-price')),
                ('expire', models.DateTimeField(verbose_name='Expire Date')),
            ],
            options={
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='Kala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('mini_description', models.CharField(max_length=200)),
                ('pic0', models.ImageField(default='no-image.jpg', height_field='image_height', upload_to='static/images/products/20241106-055231', width_field='image_width')),
                ('pic1', models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20241106 - 055231')),
                ('pic2', models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20241106 - 055231')),
                ('pic3', models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20241106 - 055231')),
                ('pic4', models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20241106 - 055231')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('image_width', models.PositiveIntegerField(default=401, editable=False)),
                ('image_height', models.PositiveIntegerField(default=401, editable=False)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand', to='shop.brand', verbose_name='Brand')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='KalaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Product Materials', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Product Materials',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter title for Post', max_length=100)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('body', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('pic', models.ImageField(blank=True, default='no-image.jpg', height_field='image_height', null=True, upload_to='static/images/posts/20241106-055231', width_field='image_width')),
                ('image_width', models.PositiveIntegerField(blank=True, default=401, editable=False, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, default=401, editable=False, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Post',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_no', models.CharField(help_text='Enter a product size', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Product Sizes',
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.kala')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Wishlist',
            },
        ),
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FollowUpCode', models.CharField(default='1520241106055231', max_length=20)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(max_length=500)),
                ('zip_code', models.CharField(max_length=10, verbose_name='Zip Code')),
                ('city', models.CharField(max_length=50)),
                ('total_price', models.BigIntegerField(help_text='Total Price With offers & Coupons')),
                ('send_price', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('total', models.BigIntegerField(help_text='Total Price With offers, Coupons, tax & send price.')),
                ('desc', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('sent', models.CharField(choices=[('T', 'Package sent'), ('B', 'Back to Store'), ('F', 'Package Wait for send')], default='F', help_text='Is package sent?', max_length=1, verbose_name='Send Status')),
                ('products', models.ManyToManyField(to='shop.cart', verbose_name='Products')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.states')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
            ],
            options={
                'verbose_name_plural': 'Sold',
            },
        ),
        migrations.CreateModel(
            name='ProductComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('T', "It's Ok"), ('W', 'Waiting')], default='W', max_length=1)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.kala')),
            ],
            options={
                'verbose_name_plural': 'Product Comments',
            },
        ),
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('T', "It's Ok"), ('W', 'Waiting')], default='W', max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.post')),
            ],
            options={
                'verbose_name_plural': 'Post Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KalaInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField(verbose_name='Price')),
                ('off', models.IntegerField(default=0)),
                ('instock', models.IntegerField()),
                ('kala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kala_instance', to='shop.kala')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product Instances',
            },
        ),
        migrations.AddField(
            model_name='kala',
            name='category',
            field=models.ForeignKey(help_text='category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Category', to='shop.kalacategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='kala',
            name='color',
            field=models.ManyToManyField(help_text='Select Color of the product', to='shop.color'),
        ),
        migrations.AddField(
            model_name='kala',
            name='material',
            field=models.ManyToManyField(help_text='Select Material of the Product', to='shop.materials'),
        ),
        migrations.AddField(
            model_name='kala',
            name='size',
            field=models.ManyToManyField(help_text='Enter Size of the product', to='shop.productsize'),
        ),
        migrations.CreateModel(
            name='Compare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.kala')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Compare',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Color', to='shop.color'),
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.coupon'),
        ),
        migrations.AddField(
            model_name='cart',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Materials', to='shop.materials'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.kala', verbose_name='Products'),
        ),
        migrations.AddField(
            model_name='cart',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Instance', to='shop.kalainstance'),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductSize', to='shop.productsize'),
        ),
        migrations.AddField(
            model_name='cart',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
