# Generated by Django 3.2.9 on 2021-12-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211207_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='states',
            options={'verbose_name_plural': 'State Tables'},
        ),
        migrations.RenameField(
            model_name='kala',
            old_name='imageheigth',
            new_name='imageheight',
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, default='no-image.jpg', height_field='imageheigth', null=True, upload_to='images/logos/', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic0',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='kalaImages/20211207-151756', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic1',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='KalaImages/20211207 - 151756'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic2',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='KalaImages/20211207 - 151756'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic3',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='KalaImages/20211207 - 151756'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic4',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='KalaImages/20211207 - 151756'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/posts/20211207-151756'),
        ),
    ]
