# Generated by Django 4.2 on 2024-11-12 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_kala_pic0_alter_kala_pic1_alter_kala_pic2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sold',
            options={'verbose_name_plural': 'Sold Orders'},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='sold',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='sold',
            old_name='desc',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='sold',
            name='FollowUpCode',
        ),
        migrations.RemoveField(
            model_name='sold',
            name='send_price',
        ),
        migrations.RemoveField(
            model_name='sold',
            name='sent',
        ),
        migrations.RemoveField(
            model_name='sold',
            name='total',
        ),
        migrations.AddField(
            model_name='sold',
            name='follow_up_code',
            field=models.CharField(editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sold',
            name='grand_total',
            field=models.BigIntegerField(default=0, help_text='Total Price With discounts, coupons, tax & shipping fee.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sold',
            name='send_status',
            field=models.CharField(choices=[('T', 'Package Sent'), ('F', 'Package Wait for send'), ('B', 'Back to Store')], default='F', help_text='Current shipping status of the order', max_length=1, verbose_name='Send Status'),
        ),
        migrations.AddField(
            model_name='sold',
            name='shipping_fee',
            field=models.IntegerField(default=0, help_text='Shipping fee applied.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cart_Product', to='shop.kala', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic0',
            field=models.ImageField(default='no-image.jpg', height_field='image_height', upload_to='static/images/products/20241112-123013', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic1',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20241112 - 123013'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic2',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20241112 - 123013'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic3',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20241112 - 123013'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic4',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20241112 - 123013'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(blank=True, default='no-image.jpg', height_field='image_height', null=True, upload_to='static/images/posts/20241112-123013', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='sold',
            name='products',
            field=models.ManyToManyField(related_name='Sold_Product', to='shop.cart', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='sold',
            name='tax',
            field=models.IntegerField(help_text='Tax applied to the total price.'),
        ),
        migrations.AlterField(
            model_name='sold',
            name='total_price',
            field=models.BigIntegerField(help_text='Total price after discounts and coupons.'),
        ),
    ]
