# Generated by Django 4.2 on 2024-11-27 08:07

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_productcomments_options_remove_cart_payed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kala',
            name='pic0',
            field=models.ImageField(default='no-image.jpg', height_field='image_height', upload_to=shop.models.kala_directory_path, width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic1',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to=shop.models.kala_directory_path),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic2',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to=shop.models.kala_directory_path),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic3',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to=shop.models.kala_directory_path),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic4',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to=shop.models.kala_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(blank=True, default='no-image.jpg', height_field='image_height', null=True, upload_to='static/images/posts/20241127-080741', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='body',
            field=models.TextField(help_text='Write your comment here.', max_length=1000, null=True),
        ),
    ]
