# Generated by Django 4.2 on 2024-10-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_kala_pic0_alter_kala_pic1_alter_kala_pic2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kala',
            name='pic0',
            field=models.ImageField(default='no-image.jpg', height_field='image_height', upload_to='static/images/products/20241014-064711', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic1',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20241014 - 064711'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic2',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20241014 - 064711'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic3',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20241014 - 064711'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic4',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20241014 - 064711'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(blank=True, default='no-image.jpg', height_field='image_height', null=True, upload_to='static/images/posts/20241014-064711', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='sold',
            name='FollowUpCode',
            field=models.CharField(default='4620241014064711', max_length=20),
        ),
        migrations.AlterField(
            model_name='sold',
            name='sent',
            field=models.CharField(choices=[('T', 'Package sent'), ('B', 'Back to Store'), ('F', 'Package Wait for send')], default='F', help_text='Is package sent?', max_length=1, verbose_name='Send Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='no-image.jpg', height_field='image_height', upload_to='static/images/profile/20241014-064711', width_field='image_width'),
        ),
    ]
