# Generated by Django 4.0 on 2022-03-01 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_kala_pic0_alter_kala_pic1_alter_kala_pic2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kala',
            name='pic0',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='static/images/products/20220301-161006', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic1',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20220301 - 161006'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic2',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20220301 - 161006'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic3',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20220301 - 161006'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic4',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='static/images/products/20220301 - 161006'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(blank=True, default='no-image.jpg', height_field='imageheight', null=True, upload_to='static/images/posts/20220301-161006', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='no-image.jpg', height_field='imageheight', upload_to='static/images/profile/20220301-161006', width_field='imagewidth'),
        ),
        migrations.CreateModel(
            name='Salled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FollowUpCode', models.CharField(default='6720220301161006', max_length=20)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(max_length=500)),
                ('zip_code', models.CharField(max_length=10, verbose_name='Zip Code')),
                ('city', models.CharField(max_length=50)),
                ('total_price', models.BigIntegerField(help_text='Total Price With offers & Coupons')),
                ('send_price', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('total', models.BigIntegerField(help_text='Total Price With offers, Coupons, tax & send price.')),
                ('desc', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('sent', models.CharField(choices=[('B', 'Back to Store'), ('T', 'Packege sent'), ('F', 'Packege Wait for send')], default='F', help_text='Is package sent?', max_length=1, verbose_name='Send Status')),
                ('products', models.ManyToManyField(to='shop.Cart', verbose_name='Products')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.states')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.user', verbose_name='Buyer')),
            ],
            options={
                'verbose_name_plural': 'Salled',
            },
        ),
    ]
